[build]
  publish = "dist"
  command = "npm run build"

# Configure secrets scanning to ignore documentation and build files
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/**,*.md,scripts/**,.env.example"
  SECRETS_SCAN_ENABLED = "true"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
